services:
  web:
    restart: unless-stopped
    build: .
    pull_policy: build
    # ports:
    #   - 8000:80
    volumes:
      - ./prj:/app

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.wt-ay-http.rule=Host(`ay.gawt.dtcloud.cz`)"
      - "traefik.http.routers.wt-ay-http.entrypoints=web"
      - "traefik.http.routers.wt-ay-http.middlewares=wt-ay-redirect-https@docker"

      - "traefik.http.middlewares.wt-ay-redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.wt-ay-redirect-https.redirectscheme.permanent=true"

      - "traefik.http.routers.wt-ay-https.rule=Host(`ay.gawt.dtcloud.cz`)"
      - "traefik.http.routers.wt-ay-https.entrypoints=websecure"
      - "traefik.http.routers.wt-ay-https.tls=true"
      - "traefik.http.routers.wt-ay-https.tls.certresolver=letsencrypt"

  static:
    image: nginx:alpine
    restart: unless-stopped

    volumes:
      - ./prj/staticfiles:/usr/share/nginx/html/static:ro

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.wt-ay-static-http.rule=Host(`ay.gawt.dtcloud.cz`) && PathPrefix(`/static`)"
      - "traefik.http.routers.wt-ay-static-http.entrypoints=web"
      - "traefik.http.routers.wt-ay-static-http.middlewares=wt-ay-static-redirect-https@docker"

      - "traefik.http.middlewares.wt-ay-static-redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.wt-ay-static-redirect-https.redirectscheme.permanent=true"

      - "traefik.http.routers.wt-ay-static-https.rule=Host(`ay.gawt.dtcloud.cz`) && PathPrefix(`/static`)"
      - "traefik.http.routers.wt-ay-static-https.entrypoints=websecure"
      - "traefik.http.routers.wt-ay-static-https.tls=true"
      - "traefik.http.routers.wt-ay-static-https.tls.certresolver=letsencrypt"

networks:
  default:
    name: proxy
    external: true
